Algoritmo "L01A"
// Disciplina   : Lógica de programação com visualg
// Professor   : Jailson Santos da Costa 
// Descrição   : Converter temperatura de Celsius para Farenheigt
// Autor(a)    : Samuel Martins Aranha
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
F: real
C: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva ("Digite a temperatura atual em Celsius: ")
leia(C)
F<-(9*C+160)/5
escreval ("A temperatura: ", "C°",C)
escreva ("Em Farenheight é: ", "F°", F)





Fimalgoritmo