Algoritmo "L01f"
// Disciplina  : Lógica de programação com VisualG e JavaScript
// Professor   : Jailsons Santos da costa
// Descrição   : Trocar os valores atribuídos
// Autor(a)    : Samuel Martins Aranha
// Data atual  : 05/04/2026
Var
// Seção de Declarações das variáveis 
   a:caractere
   b:caractere
   t:caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite uma letra: ")
leia(A)
escreval("Digite outra letra: ")
leia(b)
t<-a
a<-b
b<-t
escreval("Os respectivos valores são: ")
escreval(A)
escreval(B)

Fimalgoritmo