Algoritmo "L01g"
// Disciplina   : lógica de programação com visualg e JavaScript
// Professor   : Jailson Santos da Costa
// Descrição   : soma e multiplica 4 valores entre si
// Autor(a)    : Samuel Martins Aranha
// Data atual  : 05/04/2026
Var
// Seção de Declarações das variáveis 

a:real
b:real
c:real
d:real
amaisb:real
amaisc:real
amaisd:real
bmaisc:real
bmaisd:real
cmaisd:real
avezesb:real
avezesc:real
avezesd:real
bvezesc:real
bvezesd:real
cvezesd:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Digite um número: ")
leia(a)
escreval("Digite outro número: ")
leia(b)
escreval ("Digite outro número: ")
leia(c)
escreval ("Digite outro número: ")
leia(d)
amaisb<- a+b
amaisc<- a+c
amaisd<- a+d
bmaisc<- b+c
bmaisd<- b+d
cmaisd<- c+d
avezesb<- a*b
avezesc<- a*c
avezesd<- a*d
bvezesc<- b*c
bvezesd<- b*d
cvezesd<- c*d
escreval (amaisb)
escreval (amaisc)
escreval (amaisd)
escreval (bmaisc)
escreval (bmaisd)
escreval (cmaisd)
escreval (avezesb)
escreval (avezesc)
escreval (avezesd)
escreval (bvezesc)
escreval (bvezesd)
escreval (cvezesd)




Fimalgoritmo