Algoritmo "L01M"
// Disciplina   : Lógica de programação com visualg
// Professor   : Jailson Santos da Costa 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Samuel Martins Aranha
// Data atual  : 14/04/2026
Var
// Seção de Declarações das variáveis 


A:real
B:real
C:real
resultado_final:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Digite um valor")
leia (A)
escreval ("Digite um valor")
leia(B)
escreval ("Digite um valor")
leia (C)

resultado_final<- (A+B+C)^2

escreval ("O quadrado da soma destes três valores é: ", resultado_final)



Fimalgoritmo