Algoritmo "L02K"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Santo de nascimento
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Samuel Martins Aranha
// Data atual  : 16/04/2026
Var
// Seção de Declarações das variáveis


numero: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


escreva ("Digite um número: ")
leia(numero)

se numero>3 entao
senao
escreval (numero)

fimse

Fimalgoritmo