Algoritmo "AreadoCirculo"
// Disciplina   : Lógica de programação com visualg
// Professor   : Jailson Santos da Costa 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Samuel Martins Aranha
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 

raio: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Digite um valor:  ")
leia(raio)

escreva ("A área do circulo é:", pi*raio^2 )




Fimalgoritmo