Algoritmo "AreaLosango"
// Disciplina   : Lógica de programação com visualg
// Professor   : Jailson Santos da Costa 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 

diagonal_maior_losango: inteiro
diagonal_menor_losango: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva ("Digite quando mede a diagonal maior: ")
leia(diagonal_maior_losango)
escreva ("Digite quando mede a diagonal menor: ")
leia(diagonal_menor_losango)

escreval ("A área do Losango é: ", (diagonal_maior_losango*diagonal_menor_losango)/2)



Fimalgoritmo