Algoritmo "ConverterTemperaturaEmCelsius "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 


f:real
c:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreva ("Digite a temperatura em Farenheight ")
leia(f)

c<-(c*9/5)+32

escreval ("A temperatura em Farenheight é: ", "F°", f)
escreva ("A temperatura em Celsius é: ", "C°", c)




Fimalgoritmo