Algoritmo "MediaTresValores"
// Disciplina   : Lógica de programação com visualg
// Professor   : Jailson Santos da Costa 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Samuel Martins Aranha
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 

valor1, valor2, valor3: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


escreva ("Digite um valor: ")
leia(valor1)
escreva ("Digite outro valor: ")
leia (valor2)
escreva ("Digite outro valor: ")
leia(valor3)

escreva (" A média desse três valores é: ", (valor1+valor2+valor3)/3 )


Fimalgoritmo