Algoritmo "semnome"
// Disciplina   : Lógica de programação com visualg
// Professor   : Jailson Santos da Costa 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
base: real
altura: real
perimetro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva ( "Digite a base para calcular o perímetro do Retângulo: ")
leia (base)
escreva ("Digite a altura para calcular o perímetro do Retângulo: ")
leia(altura)

perimetro<- 2*(base+altura)

escreva ("O perimetro do retângulo é: ", perimetro)


Fimalgoritmo