Algoritmo "L0B1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
f, c: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva ("Digite a temperatura: ")
leia(f)

c<-(f-32)*(5/9)

escreva  ("F°",f, " em Celsius é: ", "C°", c)



Fimalgoritmo