Algoritmo "L03b"
// Disciplina   : [Linguagem e Lógica de Programação do visualg]
// Professor   : jailson santos da costa
// Descrição   : somar e exibir a som de 0 a 100
// Autor(a)    : Samuel Martins Aranha
// Data atual  : 06/04/2026
Var
   // Seção de Declarações das variáveis

   contador: inteiro
   numero: inteiro
   somadora: inteiro
   resultado : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador<- 1
   somadora<- 0
   enquanto contador <100 faça
      contador<-contador+1
      somadora<- contador+somadora
      escreva(somadora)
   fimenquanto



Fimalgoritmo