Algoritmo "L03c"
// Disciplina   : Lógica de programação com visualg
// Professor   : Jailson Santos da Costa
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Samuel Martins Aranha
// Data atual  : 11/04/2026
Var
   // Seção de Declarações das variáveis
   numeros: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("Os números pares são")
   numeros<-0
   enquanto numeros<500 faça
      se numeros mod 2 = 0 entao
         numeros<-numeros+1
         escreval(numeros)
      senao
         escreval("")
         numeros<-numeros+1
    fimse
   fimenquanto




Fimalgoritmo
